version: '3.9'

services:
    db:
        image: mongo
        env_file:
          - ./docker-compose/mongodb/.env

    python:
        build: ./docker-compose/python
        command: uvicorn main:app --host "0.0.0.0" --port 8080 --reload 
        depends_on:
          - db
        volumes:
          - ./app:/usr/src/app
        ports:
          - "8080:8080"
        environment:
          DATABASE_URL: mongodb://mongo:mongo@mongo

networks:
    pmapi:
        external: true
